;METADATA=(Diff=true, UseCommands=true)
[ServerSettings]
DifficultyOffset=1.0
DinoDamageMultiplier=1.05
XPMultiplier=1.5
TamingSpeedMultiplier=6.0
PlayerCharacterWaterDrainMultiplier=0.75
PlayerCharacterFoodDrainMultiplier=0.75
HarvestHealthMultiplier=1.25
PvEStructureDecayPeriodMultiplier=4.0
ResourcesRespawnPeriodMultiplier=0.75
RCONEnabled=True
RCONPort=27002
RCONServerGameLogBuffer=600
AdminListURL="http://www.bukanier.org/data/asa/admins.txt"
AutoSavePeriodMinutes=1800
BanListURL="http://www.bukanier.org/data/asa/banlist.txt"
CustomDynamicConfigUrl="http://www.bukanier.org/data/asa/dynamicconfig_scorchedearth.ini"
OverrideOfficialDifficulty=5.0
PreventOfflinePvP=False
PreventOfflinePvPInterval=3600
PreventSpawnAnimations=True
ServerAdminPassword=xxx
serverPVE=False
NPCNetworkStasisRangeScalePlayerCountStart=20
NPCNetworkStasisRangeScalePlayerCountEnd=30
NPCNetworkStasisRangeScalePercentEnd=0.5
AllowHideDamageSourceFromLogs=True
AllowHitMarkers=True
AllowThirdPersonPlayer=True
AutoCreateTribes=True
EnablePvPGamma=True
ImplantSuicideCD=28800
KickIdlePlayersPeriod=1800
OxygenSwimSpeedStatMultiplier=1
ServerCrosshair=True
ShowFloatingDamageText=False
ShowMapPlayerLocation=True
TribeNameChangeCooldown=1440
AutoDestroyStructures=True
AutoDestroyOldStructuresMultiplier=4.0125
DisableStructureDecayPvE=False
FastDecayUnsnappedCoreStructures=True
OnlyDecayUnsnappedCoreStructures=False
OnlyAutoDestroyCoreStructures=True
PvPStructureDecay=True
PvPDinoDecay=True
DisableDinoDecayPvE=False
AutoDestroyDecayedDinos=True
PvEDinoDecayPeriodMultiplier=4.0
AllowCrateSpawnsOnTopOfStructures=True
AllowCaveBuildingPvP=True
AllowCaveBuildingPvE=True
AlwaysAllowStructurePickup=True
EnableExtraStructurePreventionVolumes=True
MaxGateFrameOnSaddles=2
PerPlatformMaxStructuresMultiplier=1
PlatformSaddleBuildAreaBoundsMultiplier=1
PreventTemplateOnSaddle=True
PvEAllowStructuresAtSupplyDrops=True
StructurePickupHoldDuration=0.5
StructurePickupTimeAfterPlacement=30
TheMaxStructuresInRange=8500
EnableCryopodNerf=False
EnableCryoSicknessPVE=False
AllowCryoFridgeOnSaddle=False
DisableCryopodEnemyCheck=True
DisableCryopodFridgeRequirement=True
CryopodNerfDamageMult=0.1
CryopodNerfDuration=10
CryopodNerfIncomingDamageMultPercent=0.25
AllowAnyoneBabyImprintCuddle=False
AllowFlyerCarryPvE=True
DestroyTamesOverTheSoftTameLimit=False
ForceGachaUnhappyInCaves=True
MaxPersonalTamedDinos=175
MaxTamedDinos=3000
MaxTamedDinos_SoftTameLimit=3000
MaxTamedDinos_SoftTameLimit_CountdownForDeletionDuration=604800
RaidDinoCharacterFoodDrainMultiplier=1.0
ClampItemStats=True
ClampItemSpoilingTimes=True
ClampResourceHarvestDamage=True
UseOptimizedHarvestingHealth=True
ItemStackSizeMultiplier=1
StructurePreventResourceRadiusMultiplier=1
CropDecaySpeedMultiplier=0.75
CropGrowthSpeedMultiplier=1.25
CosmeticWhitelistOverride="http://www.bukanier.org/data/asa/CosmeticWhitelist.txt"
MaxTributeDinos=24
MaxTributeItems=96
TributeItemExpirationSeconds=259200
TributeDinoExpirationSeconds=259200
MaxTrainCars=4
LimitBunkersPerTribe=true
LimitBunkersPerTribeNum=1
AllowBunkersInPreventionZones=false
AllowRidingDinosInsideBunkers=true
AllowBunkerModulesAboveGround=false
AllowDinoAIInsideBunkers=true
AllowBunkerModulesInPreventionZones=false
MinDistanceBetweenBunkers=3000.0
EnemyAccessBunkerHPThreshold=0.25
BunkerUnderHPThresholdDmgMultiplier=0.05
CryoHospitalHoursToRegenHP=1.0
CryoHospitalHoursToRegenFood=24.0
CryoHospitalHoursToDrainTorpor=1.0
CryoHospitalMatingCooldownReduction=2.0
BloodforgeReinforceExtraDurability=0.3
BloodforgeReinforceResourceCostMultiplier=3.0
BloodforgeReinforceSpeedMultiplier=0.1
StartTimeHour=-1
OverrideSecondsUntilBuriedTreasureAutoReveals=1209600
OutpostSigilRewardMultiplier=1

[ScalabilityGroups]
sg.ResolutionQuality=75
sg.ViewDistanceQuality=1
sg.AntiAliasingQuality=1
sg.ShadowQuality=2
sg.GlobalIlluminationQuality=3
sg.ReflectionQuality=3
sg.PostProcessQuality=1
sg.TextureQuality=2
sg.EffectsQuality=1
sg.FoliageQuality=2
sg.ShadingQuality=3
sg.LandscapeQuality=0

[/Script/ShooterGame.ShooterGameUserSettings]
AdvancedGraphicsQuality=0
MasterAudioVolume=1.000000
MusicAudioVolume=0.800000
SFXAudioVolume=1.000000
VoiceAudioVolume=1.000000
SoundUIAudioVolume=1.000000
CharacterAudioVolume=1.000000
StructureTooltipMaxSpeedMultiply=0.000000
UIScaling=1.000000
UIQuickbarScaling=0.750000
CameraShakeScale=0.650000
bFirstPersonRiding=False
bThirdPersonPlayer=True
bShowStatusNotificationMessages=True
TrueSkyQuality=0.270000
FOVMultiplier=1.000000
GroundClutterDensity=1.000000
bFilmGrain=False
bMotionBlur=True
bUseGamepadSpeaker=True
bUseDFAO=False
bUseSSAO=False
bShowChatBox=True
bCameraViewBob=True
bInvertLookY=False
bFloatingNames=True
bChatBubbles=True
bHideServerInfo=False
bJoinNotifications=False
bDisableNameYourTamePopup=False
MinimalFloatingNameSetting=False
bCraftablesShowAllItems=False
bLocalInventoryItemsShowAllItems=False
bLocalInventoryCraftingShowAllItems=True
bRemoteInventoryItemsShowAllItems=False
bRemoteInventoryCraftingShowAllItems=False
bCustomCosmeticsShowAllItems=False
bRemoteInventoryShowEngrams=True
bEnableLowLightEnhancement=False
bEnableFluidInteraction=False
bDisableHLOD=False
bCinematicLightingMode=False
LookLeftRightSensitivity=1.000000
LookUpDownSensitivity=1.000000
TPVCameraHorizontalOffsetFactor=0.000000
GraphicsQuality=0
ActiveLingeringWorldTiles=10
ClientNetQuality=3
TheGammaCorrection=0.500000
LastServerSearchType=0
LastServerSort=2
LastPVESearchType=-1
LastDLCTypeSearchType=-1
LastDLCTypeSearchString=
LastServerSortAsc=True
LastAutoFavorite=True
ShowPlayerServers=False
LastServerSearchHideFull=False
LastServerSearchProtected=False
LastPlatformSpecificServerSearch=False
HideItemTextOverlay=True
bForceShowItemNames=False
bDistanceFieldShadowing=True
bDisableShadows=False
LODScalar=1.000000
bToggleToTalk=False
HighQualityMaterials=True
HighQualitySurfaces=True
bTemperatureF=False
bDisableTorporEffect=False
bChatShowSteamName=True
bChatShowTribeName=True
bReverseTribeLogOrder=False
EmoteKeyBind1=0
EmoteKeyBind2=0
bNoBloodEffects=False
bLowQualityVFX=False
bSpectatorManualFloatingNames=False
bSuppressAdminIcon=False
bUseSimpleDistanceMovement=False
bHasSavedGame=True
bDisableMeleeCameraSwingAnims=False
bPreventInventoryOpeningSounds=False
bPreventBiomeWalls=False
bPreventHitMarkers=False
bPreventCrosshair=False
bPreventColorizedItemNames=False
bHighQualityLODs=False
bExtraLevelStreamingDistance=False
bEnableColorGrading=False
VSyncMethod=1
DOFSettingInterpTime=0.000000
LastJoinedSessionPerCategory=" "
LastJoinedSessionPerCategory=" "
LastJoinedSessionPerCategory=" "
LastJoinedSessionPerCategory=" "
LastJoinedSessionPerCategory=" "
LastJoinedSessionPerCategory=" "
LastJoinedSessionPerCategory=" "
LastJoinedSessionPerCategory=" "
LastJoinedSessionPerCategory=" "
LastSessionCategoryJoined=-1
bDisableMenuTransitions=False
bEnableInventoryItemTooltips=True
bRemoteInventoryShowCraftables=False
bNoTooltipDelay=False
LocalItemSortType=0
LocalCraftingSortType=0
bCustomCosmeticDefaultItemsTab=False
bCustomCosmeticLocalTabExpanded=False
RemoteItemSortType=0
RemoteCraftingSortType=0
VersionMetaTag=4
ShowExplorerNoteSubtitles=False
DisableMenuMusic=False
DisableDefaultCharacterItems=False
DisableLoadScreenMusic=False
DisableCosmeticsDynamicDownloading=False
bRequestDefaultCharacterItemsOnce=False
bHasSeenGen2Intro=False
CinematicForNoteShouldReset=()
bHasSetupDifficultySP=False
bHasSetupVisualSettings=False
agreedToTerms=()
DynamicDownloadSpeed=500
bHasRunAutoSettings=False
bHideFloatingPlayerNames=False
bHideGamepadItemSelectionModifier=False
bToggleExtendedHUDInfo=False
PlayActionWheelClickSound=True
PlayHUDRolloverSound=True
CompanionReactionVerbosity=3
EnableEnvironmentalReactions=True
EnableRespawnReactions=True
EnableDeathReactions=True
EnableSayHelloReactions=True
EnableEmoteReactions=True
EnableMovementSounds=True
DisableSubtitles=False
bEnableASACamera=True
ConsoleAccess=False
CompanionSubtitleVerbosityLevel=3
CompanionIsHiddenState=False
MaxAscensionLevel=0
bHostSessionHasBeenOpened=False
bForceTPVCameraOffset=False
bDisableTPVCameraInterpolation=False
bEnableHDROutput=False
HDRDisplayMinLuminance=-4.000000
HDRDisplayMidLuminance=20.000000
HDRDisplayMaxLuminance=1400.000000
FoliageInteractionDistance=0.010000
FoliageInteractionDistanceLimit=0.500000
FoliageInteractionQuantityLimit=0.500000
bFPVClimbingGear=False
bFPVGlidingGear=False
bHasInitializedScreenPercentage=False
CameraZoomPerDinoNameTag=()
CameraHeightPerDinoNameTag=()
PhotomodePresets_Camera=()
PhotomodePresets_Movement=()
PhotomodePresets_Splines=()
PhotomodePresets_PPs=()
PhotomodePresets_Targeting=()
PhotomodeLastUsedSettings=()
MaxLastDeathMark=5
bSaveLastDeathMark=True
bShowPingsOnMap=True
bShowDinosOnMap=True
bShowWaypointsOnMap=True
bShowPlayersOnMap=True
bShowBedsOnMap=True
AimAssistStrengthMultiplier=1.000000
bForceShowRadialWheelTexts=False
bHideStructurePlacementCrosshair=False
SavedMainMapZoom=1.000000
SavedOverlayMapZoom=1.000000
bMinimalUI=False
FloatingTooltipStructureMode=DEFAULT
FloatingTooltipDinoMode=DEFAULT
FloatingTooltipDroppedItemsMode=DEFAULT
FloatingTooltipPlayerMode=DEFAULT
TopNotificationMode=DEFAULT
ItemNotificationMode=MINIMAL
HideEnemyStructureCosmeticsMode=NONE
bMinimapOverlayUseLowOpacity=False
FilterTypeInventoryLocal=9
FilterTypeInventoryRemote=9
FilterTypeCustomCosmeticItems=0
FilterTypeCustomCosmeticSkins=0
bUseGamepadAimAssist=RangeWeaponAlwaysOn
Gamma1=2.200000
Gamma2=3.000000
bDisableBloom=True
bDisableLightShafts=False
bUseLowQualityLevelStreaming=True
bUseDistanceFieldAmbientOcclusion=False
bPreventItemCraftingSounds=False
bHighQualityAnisotropicFiltering=False
AmbientSoundVolume=1.000000
bUseOldThirdPersonCameraTrace=False
bUseOldThirdPersonCameraOffset=False
bShowedGenesisDLCBackground=False
bShowedGenesis2DLCBackground=False
bHasStartedTheGameOnce=False
bViewedAnimatedSeriesTrailer=False
bViewedARK2Trailer=False
bShowRTSKeyBinds=True
bHasCompletedGen2=False
bEnableFootstepDecals=False
bEnableFootstepParticles=False
bShowInfoButtons=True
bDisablePaintings=False
StopExplorerNoteAudioOnClose=False
bVibration=True
bUIVibration=False
radialSelectionSpeed=0.650000
bDisableVirtualCursor=False
PreventDetailGraphics=False
GroundClutterRadius=0
HFSQuality=0
bMenuGyro=False
gyroSensitivity=0.500000
virtualCursorSensitivity=0.500000
BubbleParticlesMultiplier=1.000000
CrosshairScale=1.000000
CrosshairOpacity=1.000000
CrosshairColor=(R=1.000000,G=1.000000,B=1.000000,A=1.000000)
CrosshairColorPickerValue=(X=0.000000,Y=0.000000)
CrosshairColorOverEnemy=(R=0.000000,G=0.376471,B=1.000000,A=1.000000)
CrosshairColorPickerValueOverEnemy=(X=0.010000,Y=0.500000)
CrosshairColorOverAlly=(R=0.000000,G=1.000000,B=0.000000,A=1.000000)
CrosshairColorPickerValueOverAlly=(X=0.260000,Y=0.440000)
CrosshairColorHitmark=(R=1.000000,G=0.000000,B=0.000000,A=1.000000)
CrosshairColorPickerValueHitmark=(X=0.010000,Y=0.640000)
CurrentCameraModeIndex=2
CurrentDinoCameraModeIndex=1
bShowAmbientInsectsVFX=True
TextChatFilterType=0
VoiceChatFilterType=0
bAutomaticallyCreateWaypointOnTamingCreatures=True
bAutomaticallyCreatePOIOnDeath=True
EnableDLSS=0
bEnableDLFG=False
bEnableReflex=True
SuperResolutionQualityLevel=0
bOCIOIsEnabled=True
OCIOAsset=/Game/ASA/Environment/Common/Color/OCIO_aces_v13_cg.OCIO_aces_v13_cg
OCIOColorSpace=0
OCIODisplayView=0
bStreamlineInitializePlugin=False
bUseVSync=True
bUseDynamicResolution=False
ResolutionSizeX=1280
ResolutionSizeY=720
LastUserConfirmedResolutionSizeX=1280
LastUserConfirmedResolutionSizeY=720
WindowPosX=-1
WindowPosY=-1
FullscreenMode=1
LastConfirmedFullscreenMode=1
PreferredFullscreenMode=1
Version=5
AudioQualityLevel=0
LastConfirmedAudioQualityLevel=0
FrameRateLimit=60.000000
DesiredScreenWidth=1280
DesiredScreenHeight=720
LastUserConfirmedDesiredScreenWidth=1280
LastUserConfirmedDesiredScreenHeight=720
LastRecommendedScreenWidth=-1.000000
LastRecommendedScreenHeight=-1.000000
LastCPUBenchmarkResult=-1.000000
LastGPUBenchmarkResult=-1.000000
LastGPUBenchmarkMultiplier=1.000000
bUseHDRDisplayOutput=False
HDRDisplayOutputNits=1000
bUserMotionBlur=False
bTextChatBubbles=True
bReceiveDiscordNotifications=True
bReceiveDiscordFriendRequests=True
VSyncModeType=0
bDontReduceGameResolutionInInventory=False
bDisableVirtualKeyboard=False
SelectedMainMenuIntro=Auto
GUI3DWidgetQuality=0.000000
bShowMissionsOnMap=True
ScreenPercentage=0.500000
bHasLoadedLostColonyMainMenuOnce=False
FrameMultiplier=4

[/Script/Engine.GameUserSettings]
bUseDesiredScreenHeight=False

[SessionSettings]
SessionName=bukanier.org (Scorched Earth) - PVP

[MessageOfTheDay]
Duration=20
Message=Wir sind ein PVE/PVP Cluster. The Island ist unsere Heimatkarte mit PVE, die anderen Karten sind Gentleman-PVP! Baue ein Hypers Offline Raid Protection (ORP)! \n\nWeitere Infos: <RichColor Color="1, 0, 0, 1">www.bukanier.org</>

[/Script/Engine.GameSession]
MaxPlayers=30

[Shiny]
DinoLevelMax=175
MaxNumShinies=8
NumSearchLoops=15
LocationPrecision=2
LocationPrecisionRange=6
RequireTracker=True
UnlockTekOnKill=False
TekNumUnlock=0
TekNumUnlockAlpha=0
EnragedLevelMultiplier=2.0

[ShinyDiscord]
TitlePrefix=:sauropod:
WebhookURL="https://discord.com/api/webhooks/xxx"

[Trojan]
Webhook_ID_Token=xxx
Stop_Breeding_Gender=1

[HypersORP]
OrpRadius=12000
OrpActivationTimer=1800
OrpOfflineDamage=2.5
OrpStructuresHP=3.0
OrpStrLimit=1
OrpDecayTimer=2764800
ORPInfiniteAmmo=True
ORPGoldTurrets=True
UsePrograms=False

[CybersPullIt]
DisableResourcePulling=false
ResourcePullRangeInFoundations=25
ResourceTransferCooldown=1

[SFM]
DisableExtraWeightReduction=True
AnkyAndDoediNormalAttack=False
RespectWeightLimit=False
UseStaminaInFarmMode=False

[DerDinoFinder]
AllowClientLanguage=False
RestrictAdmins=False
IsAdminOnly=False
UnlockLevel=10
MarkerLimit=20
ScanCooldown=300
DisableSearching=False
DisableTracking=True
DisableLevelFilter=False
DefaultMaxLevel=150
DefaultMinLevel=5
LevelFilterBound=185
DisableAgeFilter=False
DisableGenderFilter=False
DisableDinoStats=False
DisableTraitSearching=True
DisableTraitOnMap=False
DisableVariantFilter=True
DisableVariantName=True

[AdjustableCryo]
AdminIgnoreCryoSickness=true
CryoSicknessTime=60.0
DisableCryoSickness=false

[Simple_Trade]
SkipModID=1214404,928548,928501,935408,937154,1304113,959521,930381,928661,1058720,1163881,1445744,

[Startup]
FrameGenerationMethod=-1
FrameGenerationMultiplier=2
SuperResolutionSystem=-1
FSRQualityMode=4
DLSSQualityMode=7
ReflexEnabled=-1

